### ISSUE TITLE
Jokes agent starts but doesn't appear in alpha.own.space

### ISSUE THREAD

**Issue by learngh1** [own-dev/own-agent-open#9]
It seems all of the parts (agent-service, agent-handler and engine) start and work, but I can't hire jokes-agent via front-end app on http://alpha.own.space - jokes-agent isn't present in "Invite Artificial Agents" nor in "Invite other agents" parts of the web site.

Logs after run "screen python3 agents_starter.py":

```
* Running on http://0.0.0.0:10110/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:10102/ (Press CTRL+C to quit)
192.168.1.3 - - [05/Jul/2019 11:47:01] "GET /ping HTTP/1.1" 200 -
127.0.0.1 - - [05/Jul/2019 11:47:01] "GET /ping HTTP/1.1" 200 -
192.168.1.3 - - [05/Jul/2019 11:47:02] "GET /ping HTTP/1.1" 200 -
192.168.1.3 - - [05/Jul/2019 11:47:02] "POST /addNewAgentInstance?agent_number=0&ip=http://192.168.1.3:10102 HTTP/1.1" 200 -
```

Logs after run "python3 agents_platform/engine.py &":
```
(ownenv) bob@upc:/own-agent$ 2019.07.05 11:50:38 [Info] [own_adapter] AGENTS_ENVIRONMENT is not defined. Setting it to test.
2019.07.05 11:50:38 [Debug] [jokes] New agent-service [jokes] is registered
2019.07.05 11:50:39 [Debug] [jokes] jokes started websocket
2019.07.05 11:50:39 [Info] [jokes] jokes_agent's websocket is open
(ownenv) bob@upc:/own-agent$ 2019.07.05 11:50:43 [Debug] [jokes] {"contentType":"application/vnd.uberblik.liveUpdatePingMessage+json","time":1562327443789,"connectedClients":[]}
2019.07.05 11:50:58 [Debug] [jokes] {"contentType":"application/vnd.uberblik.liveUpdatePingMessage+json","time":1562327458789,"connectedClients":[]}
```
Agents platform generates some data in firestore database after launch:
```
/agentsPlatform/jokes_test_1.0.0/agentHandlers/e92EvBICM0rOjNthimqO 
address: "http://192.168.1.3:10110"
currentNumberOfAgents: 1
maxNumberOfTasks: 10
numberOfFails: 0
numberOfTasks: 0
```
Also, after I open "Add new item" form on alpha.own.space board, there are some changes in the log:
```
2019.07.05 12:06:29 [Debug] [jokes] {"contentType":"application/vnd.uberblik.liveUpdateElementAdded+json","path":"/boards/1961/elements/7620"}
2019.07.05 12:06:30 [Debug] [jokes] {"contentType":"application/vnd.uberblik.liveUpdateBoardOverviewChanged+json","path":"/boards/1961"}
2019.07.05 12:06:30 [Debug] [jokes] {"contentType":"application/vnd.uberblik.liveUpdateActivitiesUpdated+json","path":"/boards/1961","affectsAllEntries":false}
```
So, the question is - how is it supposed to test jokes-agent? Is it normal that jokes-agent isn't visible in available to hire list of agents?

**Comment by denef** [comment]
To test Jokes (or any other) Agent via the front-end perform the following steps:

1. Register at http://alpha.own.space (later on I will reference it as "the system")

2. Specify your login and password in OWN_JOKES_AGENT_LOGIN & OWN_JOKES_AGENT_PASSWORD environment variables

![image](https://user-images.githubusercontent.com/15213960/60733933-f781e600-9f56-11e9-9fd6-36803d1c166f.png)

3. Make user you registered in the system an agent

    run python3 agents_platform/cli/cli.py
    there select "1. Agent Configurations" - "2. Create a new Agent" - "1. jokes agent" - "y"

    make sure there are no errors in the logs (which may be if e.g. environment variables were not set)

    You shoud see "1. back"

    go back to the first menu (or close CLI tool and open it again)

    "3. Agent Tasks" - "2. Create a new task" - "1. Find Funny Jokes" - "y"

    make sure there are no errors in the logs (which may be if e.g. environment variables were not set)

    Open in repository file agents_platform/services/jokes_service/agent_tasks/jokes.json

    at the end of that file id of the task created in the system should appear. The agents platform will now accept queries for this task.

![image](https://user-images.githubusercontent.com/15213960/60733949-02d51180-9f57-11e9-8787-4f5225cffca7.png)


4. On http://alpha.own.space, logged in as the user created on step 1 open any board and reload the page

5. Open any empty cell, there you should see the agent named as the user you are logged in as, e.g.

![image](https://user-images.githubusercontent.com/15213960/60733968-0d8fa680-9f57-11e9-8c4f-6b46e260a476.png)

6. Click "Add" near the name of the newly created Agent Task

If Agents Platform, Agent Handler & Agent are running, when you press "save", Agent should start to process the request, and later on Agent Service will put result on the board. Which in case of Jokes Agent will be in the form of messages to the activity stream (to the right of the board)

![image](https://user-images.githubusercontent.com/15213960/60733983-16807800-9f57-11e9-9d93-61bc68c72129.png)


P.S.: At the moment we also have a front-end interface where actions described in step 3 can be implemented, but it is not yet deployed for the alpha version of the system.

**Comment by learngh1** [comment]
That helped, thanks. First time agent and task were created, but:
1) - _"repository file agents_platform/services/jokes_service/agent_tasks/jokes.json"_ wasn't appear neither in the firebase database nor in the firebase storage - storage is empty; only _"/agentsPlatform/jokes_test_1.0.0/agentHandlers/Tq0l630BMmmol9JE0J60"_ was present in the database
2) - after removing created agent configuration via CLI, I created jokes agent configuration again - this part works fine. But I'm not able to create task anymore: all "Agent Tasks" menu items ("1. list", "2. create", "4. remove") return empty list with one option "1. Back" only.

There are no errors in "logs/own_adapter". Now I can see jokes agent with my full name as a title in "Add new item" form on http://alpha.own.space, but there are no tasks

**Comment by AlNedorezov** [comment]
@learngh1 by repository file agents_platform/services/jokes_service/agent_tasks/jokes.json that file in the repository was meant: https://github.com/own-dev/own-agent-open/blob/master/agents_platform/services/jokes_service/agent_tasks/jokes.json, not something in the firebase

To be able to add task which you added before, delete the id of the agent task from the jokes.json (referenced above, also see the screenshot of the file in the previous answer)

**Comment by learngh1** [comment]
it works, thanks
